
USE [WFADBMD]

--

-- 1) ADD DBCOLCICS, CCOLCICS CI VS CS
-- 2) ADD DB_KIND_NAME
-- 3) ADD IN_IDX information ( from DC13, potentially incorrect)

DROP TABLE IF EXISTS [dbo].[DB_TBL_COL];
GO
SELECT [WSNAME] [DCNAME],
       [SERVERNAME]
      ,[SERVERCOL]
      ,[DB_NAME]
      ,[DB_KIND]
	  , CAST( CASE WHEN [DB_KIND] = 0 THEN 'UNKNOWN'
	         WHEN [DB_KIND] = 1 THEN 'HrmlConfig'
	  		 WHEN [DB_KIND] = 2 THEN 'HrmlUsers'
			 WHEN [DB_KIND] = 4 THEN 'Hrml'
			 WHEN [DB_KIND] = 16 THEN 'HrmlLocales'
			 WHEN [DB_KIND] = 32 THEN 'WST'
			 WHEN [DB_KIND] = 64 THEN 'GDPR'
			 WHEN [DB_KIND] = 128 THEN 'WST_LOOKUP'
			 WHEN [DB_KIND] = 256 THEN 'Perf'
			 ELSE 'UNKNOWN' END
			   AS NVARCHAR(16)) DB_KIND_NAME
      ,[DBCOL]
	  , CAST(CASE WHEN (CHARINDEX( '_CI_', DBCOL) > 0) THEN 'CI'
       	ELSE 'CS' END  AS NVARCHAR(2)) DBCOLCICS
      ,[TNAME]
      ,[CNAME]
      ,[CID]
      ,[CCOL]
	  , CAST(CASE WHEN (CHARINDEX( '_CI_', CCOL) > 0) THEN 'CI'
	              WHEN (CCOL IS NULL) THEN NULL
       			  ELSE 'CS' END  AS NVARCHAR(2)) CCOLCICS,
	   CAST ( CASE  WHEN TIDX.IDX_CNAME IS NULL   THEN 0
	                ELSE  1  END  AS INT) IN_IDX

	INTO [dbo].[DB_TBL_COL]
	FROM [dbo].[DB_TBL_COL_COLLATION] T0
	LEFT OUTER JOIN
	   ( SELECT DISTINCT 4 IDX_DB_KIND , TNAME IDX_TNAME, CNAME IDX_CNAME FROM [dbo].[DB_INDICES] ) TIDX
	 ON  TIDX.IDX_DB_KIND = T0.DB_KIND
	   AND TIDX.IDX_TNAME = T0.TNAME
	   AND TIDX.IDX_CNAME = T0.CNAME
GO

SELECT DB_KIND, DB_KIND_NAME FROM [dbo].[DB_TBL_COL] WHERE TNAME = 'SITE_CONFIG'

SELECT DB_KIND, DB_KIND_NAME FROM [dbo].[DB_TBL_COL] WHERE TNAME = 'SITE_CONFIG'

-- DB Collations
DROP VIEW IF EXISTS [dbo].[VW_DB_COLLATIONS];
GO

CREATE VIEW [dbo].VW_DB_COLLATIONS AS SELECT DCNAME, DB_NAME, SERVERNAME, DB_KIND,
DB_KIND_NAME, DBCOL, DBCOLCICS, COUNT( DISTINCT TNAME) NRTABLES, COUNT( DISTINCT (TNAME + CNAME) ) NRCOLS,
  COUNT ( DISTINCT CCOL )     NRCCOL,
  COUNT ( DISTINCT CCOLCICS ) NRCCOLCICS
  ,SUM ( CASE WHEN CCOL = 'Latin1_General_CS_AS' THEN 1 ELSE 0 END )         CCOL_Lat_CS
  ,SUM ( CASE WHEN CCOL = 'Latin1_General_CI_AS' THEN 1 ELSE 0 END )         CCOL_Lat_CI
  ,SUM ( CASE WHEN CCOL = 'SQL_Latin1_General_CP1_CI_AS' THEN 1 ELSE 0 END ) CCOL_SQL_CI
FROM [dbo].[DB_TBL_COL]
WHERE DB_KIND > 0
GROUP BY DCNAME, DB_NAME, SERVERNAME, DB_KIND, DB_KIND_NAME, DBCOL, DBCOLCICS;
GO

DROP VIEW IF EXISTS [dbo].[VW_DB_KIND_COLLATION];
GO

CREATE VIEW [dbo].[VW_DB_KIND_COLLATION] AS
SELECT DB_KIND_NAME
  ,SUM ( CASE WHEN DBCOL = 'Latin1_General_CS_AS' THEN 1 ELSE 0 END )         DB_Lat_CS
  ,SUM ( CASE WHEN DBCOL = 'Latin1_General_CI_AS' THEN 1 ELSE 0 END )         DB_Lat_CI
  ,SUM ( CASE WHEN DBCOL = 'SQL_Latin1_General_CP1_CI_AS' THEN 1 ELSE 0 END ) DB_SQL_CI
  ,SUM ( CCOL_Lat_CS ) CCOL_Lat_CS
  ,SUM ( CCOL_Lat_CI ) CCOL_Lat_CI
  ,SUM ( CCOL_SQL_CI ) CCOL_SQL_CI
  ,MAX (NRTABLES) MAX_NRTABLES
  ,MIN (NRTABLES) MIN_NRTABLES
  FROM [dbo].[VW_DB_COLLATIONS]
  GROUP BY DB_KIND_NAME

GO


SELECT 'Distinct Server collations homogeneous ...'
--TOWS:ServerCollations
SELECT DISTINCT SERVERCOL From  [dbo].[DB_TBL_COL_COLLATION];
GO


SELECT 'DB Collations by Kind '
--TOWS:DBCollationsByKind
--WSFIX:1,1
--WSCOLCOMMENT:DB_Lat_CS:"Nr of DBs with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:DB_Lat_CI:"Nr of DBs with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:DB_SQL_CI:"Nr of DBs with SQL_Latin1_General_CP1_CI_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CS:"Nr of Columns with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CI:"Nr of Columns with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:CCOL_SQL_CI:"Nr of Columsn with SQL_Latin1_General_CP1_CI_AS collation"
SELECT * FROM [dbo].[VW_DB_KIND_COLLATION]
GO

SELECT 'DB Collations '
--TOWS:DBCollations
--WSFIX:1,4
--WSCOLCOMMENT:DBCOL:"Database Collation"
--WSCOLCOMMENT:DB_Lat_CS:"Nr of DBs with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:DB_Lat_CI:"Nr of DBs with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:DB_SQL_CI:"Nr of DBs with SQL_Latin1_General_CP1_CI_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CS:"Nr of Columns with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CI:"Nr of Columns with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:CCOL_SQL_CI:"Nr of Columsn with SQL_Latin1_General_CP1_CI_AS collation"
SELECT T1.DB_KIND_NAME, DB_NAME, SERVERNAME, DCNAME,
 T1.DBCOL,
 T2.DB_Lat_CS,
 T2.DB_Lat_CI,
 T2.DB_SQL_CI,
 DBCOLCICS, NRTABLES, NRCOLS, NRCCOL, NRCCOLCICS , T1.CCOL_Lat_CS , T1.CCOL_Lat_CI, T1.CCOL_SQL_CI
 FROM [dbo].VW_DB_COLLATIONS T1
 LEFT OUTER JOIN [dbo].[VW_DB_KIND_COLLATION] T2
 ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
 ORDER BY T1.DB_KIND_NAME, DCNAME , DB_NAME



-- SELECT 'DB collations per DB kind homogeneous w.r.t CICS ...'
-- SELECT DISTINCT DB_KIND_NAME, DBCOLCICS FROM [dbo].VW_DB_COLLATIONS

-- SELECT 'DB kinds collations per DB kind homogeneous ...'
-- SELECT DISTINCT DB_KIND_NAME, DBCOL FROM [dbo].VW_DB_COLLATIONS ORDER BY DB_KIND_NAME

SELECT 'DB kinds with different collations CS vs CI (!) ...'
--TOWS:DBCICSCollations
SELECT DISTINCT T1.DB_KIND_NAME, T1.DBCOL, T2.DBCOL
  FROM [dbo].VW_DB_COLLATIONS T1
  INNER JOIN [dbo].VW_DB_COLLATIONS T2
  ON T1.DB_KIND_NAME =  T2.DB_KIND_NAME
  AND T1.DBCOLCICS != T2.DBCOLCICS
  AND T1.DBCOL < T2.DBCOL
 ORDER BY DB_KIND_NAME, T1.DBCOL, T2.DBCOL
GO

SELECT 'DB with different collations ...'
--TOWS:DBDiffCollations
SELECT DISTINCT T1.DB_KIND_NAME, T1.DBCOL, T2.DBCOL
  FROM [dbo].VW_DB_COLLATIONS T1
  INNER JOIN [dbo].VW_DB_COLLATIONS T2
  ON T1.DB_KIND_NAME =  T2.DB_KIND_NAME
  AND T1.DB_KIND_NAME != 'UNKNOWN'
  AND T1.DBCOL < T2.DBCOL
 ORDER BY DB_KIND_NAME, T1.DBCOL, T2.DBCOL
GO


DROP VIEW IF EXISTS [dbo].[VW_DB_COLS_DIFFERING]
GO
CREATE VIEW [dbo].[VW_DB_COLS_DIFFERING]
AS SELECT DISTINCT T1.DB_KIND_NAME, T1.DBCOL DBCOL, T2.DBCOL DBCOL_OTHER
  FROM [dbo].VW_DB_COLLATIONS T1
  INNER JOIN [dbo].VW_DB_COLLATIONS T2
  ON T1.DB_KIND_NAME =  T2.DB_KIND_NAME
  AND T1.DB_KIND_NAME != 'UNKNOWN'
  AND T1.DBCOL < T2.DBCOL
GO


 SELECT 'DB with different collations ...'
 SELECT * FROM [dbo].[VW_DB_COLS_DIFFERING]
 ORDER BY DB_KIND_NAME, DBCOL, DBCOL_OTHER

-- list infos on DBs which are messy.

SELECT 'Same kind DBs with different collations ...'

SELECT  T1.DB_KIND_NAME, T1.DBCOLCICS, T1.DBCOL, TCNT.CNT NRSAMECOLDBS, T1.DB_NAME, T1.DCNAME
FROM
 (	SELECT DISTINCT DB_KIND_NAME, DBCOLCICS, DBCOL, DB_NAME, DCNAME
	FROM [dbo].VW_DB_COLLATIONS
	WHERE DB_KIND_NAME IN ( SELECT DB_KIND_NAME FROM [dbo].[VW_DB_COLS_DIFFERING] )
	)  T1
LEFT OUTER JOIN
 (
   SELECT DB_KIND_NAME, COUNT( * ) CNT , DBCOL FROM
		(	SELECT DISTINCT DB_KIND_NAME, DBCOLCICS, DBCOL, DB_NAME, DCNAME
			FROM [dbo].VW_DB_COLLATIONS
			WHERE DB_KIND_NAME IN ( SELECT DB_KIND_NAME FROM [dbo].[VW_DB_COLS_DIFFERING] ) ) T00
	GROUP BY DB_KIND_NAME, DBCOL
  ) TCNT
ON T1.DB_KIND_NAME = TCNT.DB_KIND_NAME
AND T1.DBCOL = TCNT.DBCOL
ORDER BY DB_KIND_NAME, DBCOLCICS, DBCOL, DCNAME, DB_NAME
GO
USE WFADBMD
GO
SELECT ' Spurios tables ...'
SELECT ' DB Table Count ...'
SELECT DISTINCT DB_KIND_NAME, NRTABLES
	FROM [dbo].VW_DB_COLLATIONS WHERE DB_KIND_NAME != 'UNKNOWN'
	ORDER BY DB_KIND_NAME, NRTABLES

-- creates a table
DROP TABLE IF EXISTS [dbo].[DB_TABLES];
GO

-- tables ->
SELECT * INTO [dbo].[DB_TABLES]
FROM (
	SELECT DCNAME, SERVERNAME, (DCNAME + SERVERNAME + DB_NAME) DCDBSRV, DB_NAME, DBCOLCICS, DBCOL, DB_KIND, DB_KIND_NAME, TNAME, COUNT( DISTINCT CNAME ) NRCOLS
	,COUNT( DISTINCT  CCOL ) NRCCOL
	,COUNT( DISTINCT CCOLCICS ) NRCCOLCICS
	,SUM ( CASE WHEN CCOL = 'Latin1_General_CS_AS' THEN 1 ELSE 0 END )         CCOL_Lat_CS
    ,SUM ( CASE WHEN CCOL = 'Latin1_General_CI_AS' THEN 1 ELSE 0 END )         CCOL_Lat_CI
    ,SUM ( CASE WHEN CCOL = 'SQL_Latin1_General_CP1_CI_AS' THEN 1 ELSE 0 END ) CCOL_SQL_CI

   FROM [dbo].[DB_TBL_COL]
   WHERE DB_KIND > 0 AND DB_KIND_NAME != 'UNKNOWN'
--   AND TNAME = 'SITE_CONFIG'
   GROUP BY DCNAME, SERVERNAME, DB_NAME, DBCOLCICS, DBCOL, DB_KIND, DB_KIND_NAME, TNAME
   ) T0


-- DB Table collation overview
DROP VIEW IF EXISTS [dbo].[VW_DB_KIND_TABLE_COLLATION];
GO

CREATE VIEW [dbo].[VW_DB_KIND_TABLE_COLLATION] AS
	SELECT
	T1.DB_KIND_NAME
	,T1.TNAME
	,TCNT.CNT_DBS_OF_KIND NRDBS_OF_KIND
	,(TCNT.CNT_DBS_OF_KIND - NRDBS_WITH_TABLE) NRDBS_WO_TABLE
	,NRCOL_MIN
	,ADD_COLUMNS
	,NRCCOL
	,NRCCOLCICS
	,CCOL_Lat_CS
    ,CCOL_Lat_CI
    ,CCOL_SQL_CI
	FROM (
		SELECT
		 DB_KIND_NAME
		,TNAME
		,COUNT( DISTINCT DB_NAME + SERVERNAME ) NRDBS_WITH_TABLE
		,COUNT( DISTINCT  CCOL ) NRCCOL
		,COUNT( DISTINCT CCOLCICS ) NRCCOLCICS
		,SUM ( CASE WHEN CCOL = 'Latin1_General_CS_AS' THEN 1 ELSE 0 END )         CCOL_Lat_CS
		,SUM ( CASE WHEN CCOL = 'Latin1_General_CI_AS' THEN 1 ELSE 0 END )         CCOL_Lat_CI
		,SUM ( CASE WHEN CCOL = 'SQL_Latin1_General_CP1_CI_AS' THEN 1 ELSE 0 END ) CCOL_SQL_CI
		FROM [dbo].[DB_TBL_COL]
    	GROUP BY DB_KIND_NAME, TNAME) T1
    LEFT OUTER JOIN [dbo].[DB_KIND_COUNTS] TCNT
	  ON T1.DB_KIND_NAME = TCNT.DB_KIND_NAME
	LEFT OUTER JOIN
	  (SELECT DB_KIND_NAME,
	          TNAME,
			  MIN(NRCOL) NRCOL_MIN
			,(MAX(NRCOL) - MIN(NRCOL)) ADD_COLUMNS
			FROM
				(SELECT DB_KIND_NAME, SERVERNAME, DCNAME, DB_NAME, TNAME, COUNT(DISTINCT CNAME) NRCOL
				 FROM [dbo].[DB_TBL_COL]
				 GROUP BY DB_KIND_NAME, SERVERNAME, DCNAME, DB_NAME, TNAME ) TX
			GROUP BY DB_KIND_NAME, TNAME ) T2
	  ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
	     AND T2.TNAME = T1.TNAME
      WHERE T1.DB_KIND_NAME <> 'UNKNOWN'
GO

SELECT 'DB Tables with different collations ...'
--TOWS:DB_KIND_TableCollations
--WSFIX:1,4
--WSCOLCOMMENT:DBCOL:"Database Collation"
--WSCOLCOMMENT:NRDBS_OF_KIND:"Nr of DBs of kind without this table"
--WSCOLCOMMENT:NRDBS_WO_TABLE:"Nr of DBs of kind without this table"
--WSCOLCOMMENT:NR_COL_MIN:"Min Nr of Columns in any of this table"
--WSCOLCOMMENT:ADD_COLUMNS:"Nr of additional columns in some tables of this name"
--WSCOLCOMMENT:NRCCOL:"Nr of distinct collations (Filter != 1)"
--WSCOLCOMMENT:NRCCOLCICS:"Nr of distinct collations w.r.t. CI-CS differences (Filter != 1)"
--WSCOLCOMMENT:CCOL_Lat_CS:"Nr of Columns with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CI:"Nr of Columns with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:CCOL_SQL_CI:"Nr of Columsn with SQL_Latin1_General_CP1_CI_AS collation"
SELECT * FROM [dbo].[VW_DB_KIND_TABLE_COLLATION]
	ORDER BY DB_KIND_NAME, TNAME
GO


-- DB Table collation overview
DROP VIEW IF EXISTS [dbo].[VW_DB_TABLE_COLLATION];
GO
 CREATE VIEW [dbo].[VW_DB_TABLE_COLLATION] AS
SELECT T1.DB_KIND_NAME DB_KIND_NAME, DB_NAME, SERVERNAME, DCNAME, T1.TNAME TNAME,
  T1.DBCOL DBCOL,
   (CASE WHEN (T2.NRDBS_WO_TABLE)> 0 THEN 1
         ELSE 0 END)  SPURIOUS
 ,(NRCOLS - T2.NRCOL_MIN) NRSPURIOUS_COL
 ,NRCOLS, T1.NRCCOL, T1.NRCCOLCICS,
 T1.CCOL_Lat_CS , T1.CCOL_Lat_CI, T1.CCOL_SQL_CI  FROM [dbo].[DB_TABLES] T1
 LEFT OUTER JOIN [dbo].[VW_DB_KIND_TABLE_COLLATION] T2
 ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
 AND T1.TNAME = T2.TNAME

GO


SELECT 'DB Tables collations ...'
--TOWS:DB_TableCollations
--WSFIX:1,4
--WSCOLCOMMENT:DBCOL:"Database Collation"
--WSCOLCOMMENT:SPURIOUS:"DB may be spurious( is not in all DBs of Kind), Filter = 1"
--WSCOLCOMMENT:DB_Lat_CS:"Nr of DBs with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:NRCCOL:"Nr of distinct collations (Filter > 1)"
--WSCOLCOMMENT:NRCCOLCICS:"Nr of distinct CI-CS collations (Filter > 1)"
--WSCOLCOMMENT:CCOL_Lat_CS:"Nr of Columns with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CI:"Nr of Columns with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:CCOL_SQL_CI:"Nr of Columsn with SQL_Latin1_General_CP1_CI_AS collation"
SELECT * ,
   ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME, CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI
                       ORDER BY CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI ) RN
FROM [dbo].[VW_DB_TABLE_COLLATION]
 ORDER BY DB_KIND_NAME, TNAME ,  DBCOL, RN, DB_NAME


-- significant deviations
SELECT COUNT(*) FROM (
SELECT T1.*,
  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
                       ORDER BY CCOL_Lat_CS, CCOL_CI ) RN
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, (CCOL_Lat_CI + CCOL_SQL_CI) CCOL_CI  FROM [dbo].[VW_DB_TABLE_COLLATION]
   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
   ) T1
  ) T2 WHERE T2.RN = 1



SELECT COUNT(*) FROM (
SELECT T1.*,
  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
                       ORDER BY CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI ) RN
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI FROM [dbo].[VW_DB_TABLE_COLLATION]
   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
   ) T1
  ) T2 WHERE T2.RN = 1




SELECT 'DB Tables overview ...'
-- x --TOWS:DB_TablesSummaryCounts
 SELECT
  (SELECT COUNT(*) FROM [dbo].[VW_DB_TABLE_COLLATION]) NRTABLES
	,
-- significant deviations
(SELECT COUNT(*) FROM (
SELECT T1.*,
  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
                       ORDER BY CCOL_Lat_CS, CCOL_CI ) RN
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, (CCOL_Lat_CI + CCOL_SQL_CI) CCOL_CI  FROM [dbo].[VW_DB_TABLE_COLLATION]
   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
   ) T1
  ) T2 WHERE T2.RN = 2 ) NR_COMMON_TABLES_WITH_SIG_DIFF_COLLATION
  ,(SELECT COUNT(*) FROM (
	SELECT T1.*,
	  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
						   ORDER BY CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI ) RN
	  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI FROM [dbo].[VW_DB_TABLE_COLLATION]
	   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
	   ) T1
	  ) T2 WHERE T2.RN = 2) NR_COMMON_TABLES_WITH_DIFF_COLLATION
  ,(SELECT COUNT(*) FROM ( SELECT T1.*,
  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
                       ORDER BY CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI ) RN
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI FROM [dbo].[VW_DB_TABLE_COLLATION] ) T1
  ) T2 WHERE T2.RN = 2 ) NR_TABLES_WITH_DIFF_COLLATION
  ,(SELECT COUNT(*) FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE SPURIOUS = 1) SPURIOUS_TABLES
  ,(SELECT COUNT(*) FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRSPURIOUS_COL > 0) TABLES_WITH_SPURIOUS_COLUMNS
  ,(SELECT SUM(NRSPURIOUS_COL) FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRSPURIOUS_COL > 0) SPURIOUS_COLUMNS
  ,(SELECT COUNT(*) FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRCCOL > 1 ) TABLES_WITH_MORE_THAN_ONE_COLLATION_IN_TABLE
  ,(SELECT COUNT(*) FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRCCOLCICS > 1 ) TABLES_WITH_MORE_THAN_ONE_CICS_IN_TABLE

GO

-- SELECT * FROM [dbo].[DB_TBL_COL] WHERE TNAME = 'SITE_CONFIG' AND DB_KIND > 0 AND DB_KIND_NAME != 'UNKNOWN'
-- SELECT * FROM [dbo].[DB_TABLES] WHERE TNAME = 'SITE_CONFIG'

DROP TABLE IF EXISTS [dbo].[TNAME_COUNTS];
-- tables which are in all dbs.
SELECT *
INTO [dbo].[TNAME_COUNTS]
FROM (
SELECT DB_KIND_NAME, TNAME, COUNT( DISTINCT DCDBSRV ) NRDBS
   FROM [dbo].[DB_TABLES]
   GROUP BY DB_KIND_NAME, TNAME
   ) T0
GO

-- SELECT * FROM [dbo].[DB_TBL_COL] WHERE TNAME = 'SITE_CONFIG'
-- SELECT * FROM [dbo].[DB_TABLES] WHERE TNAME = 'SITE_CONFIG'
-- SELECT * FROM [dbo].[TNAME_COUNTS] WHERE TNAME = 'SITE_CONFIG'

-- DB KIND COUNTS
DROP TABLE IF EXISTS [dbo].[DB_KIND_COUNTS];
GO
SELECT *
   INTO [dbo].[DB_KIND_COUNTS]
   FROM (
SELECT DB_KIND_NAME, DB_KIND, COUNT( DISTINCT DCDBSRV ) CNT_DBS_OF_KIND
   FROM [dbo].[DB_TABLES]
   GROUP BY DB_KIND_NAME, DB_KIND
   ) T1
GO

SELECT DB_KIND_NAME, DB_KIND, COUNT( DISTINCT DCDBSRV ) CNT_DBS_OF_KIND
   FROM [dbo].[DB_TABLES]
   WHERE DB_KIND = 4
   GROUP BY DB_KIND_NAME, DB_KIND
GO

SELECT DISTINCT DB_KIND_NAME, DB_KIND, DCDBSRV
   FROM [dbo].[DB_TABLES]
   WHERE DB_KIND = 4
  -- GROUP BY DB_KIND_NAME, DB_KIND
      ORDER BY DCDBSRV
GO

SELECT DB_KIND_NAME, DB_KIND, CNT_DBS_OF_KIND FROM [dbo].[DB_KIND_COUNTS] WHERE DB_KIND = 4
GO
-- tables which are not in all dbs ->
DROP TABLE IF EXISTS [dbo].[SPURIOUS_TABLES];
GO

SELECT T1.DB_KIND_NAME, TNAME
  INTO [dbo].[SPURIOUS_TABLES]
  FROM [dbo].[TNAME_COUNTS] T1
  INNER JOIN [dbo].[DB_KIND_COUNTS] T2
  ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
  AND T1.NRDBS != T2.CNT_DBS_OF_KIND
GO

-- tables which are in all dbs ->
DROP TABLE IF EXISTS [dbo].[COMMON_TABLES];
GO

SELECT T1.DB_KIND_NAME, TNAME
  INTO [dbo].[COMMON_TABLES]
  FROM [dbo].[TNAME_COUNTS] T1
  INNER JOIN [dbo].[DB_KIND_COUNTS] T2
  ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
  AND T1.NRDBS = T2.CNT_DBS_OF_KIND
GO



DROP TABLE IF EXISTS [dbo].[COMMON_TBL_COL];
GO

SELECT T1.* ,
   (DCNAME + ' ' + SERVERNAME + ' ' + DB_NAME + ' ' + T1.TNAME ) DCDBSRVTBL,
   (DCNAME + ' ' + SERVERNAME + ' ' + DB_NAME ) DCDBSRV
  INTO [dbo].[COMMON_TBL_COL]
  FROM [dbo].[DB_TBL_COL]  T1
  INNER JOIN [dbo].[COMMON_TABLES]  CT
    ON T1.DB_KIND_NAME = CT.DB_KIND_NAME
	AND T1.TNAME = CT.TNAME
	WHERE DB_KIND > 0
GO

CREATE  INDEX index1 ON [dbo].[COMMON_TBL_COL] (TNAME,CNAME, DB_KIND,DB_KIND_NAME);
CREATE  INDEX i2 ON [dbo].[COMMON_TBL_COL] (TNAME,CNAME,DB_KIND_NAME);

DROP VIEW IF EXISTS [dbo].[VW_DB_KIND_COLL_DIF_COL_COUNT];

-- SELECT 'NR of Collation differences in Common Tables'
 ---
 --- TOWS:DB_KIND_CMN_TBL_COL_COLL_DIFF_CNT
GO
CREATE VIEW [dbo].[VW_DB_KIND_COLL_DIF_COL_COUNT] AS
SELECT
  TC.DB_KIND_NAME, COALESCE(DIFF_CI_CS,0) NR_COLS_DIFF_CI_CS, COALESCE(DIFF_ANY,0) NR_COLS_DIFF_ANY, NR_COLS
FROM
( SELECT DB_KIND_NAME, COUNT(*) NR_COLS FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME, CNAME  FROM [dbo].[COMMON_TBL_COL] ) T01
GROUP BY T01.DB_KIND_NAME
) TC
LEFT OUTER JOIN
( SELECT DB_KIND_NAME, COUNT(*) DIFF_CI_CS
   FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOLCICS < T2.CCOLCICS
   ) T1
) T0
GROUP BY T0.DB_KIND_NAME
 ) TA
ON TC.DB_KIND_NAME = TA.DB_KIND_NAME
LEFT OUTER JOIN
( SELECT DB_KIND_NAME, COUNT(*)	DIFF_ANY
 FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOL < T2.CCOL
   ) T1
) T0
GROUP BY T0.DB_KIND_NAME ) TB
ON TC.DB_KIND_NAME = TB.DB_KIND_NAME
-- ORDER BY DB_KIND_NAME
GO

SELECT 'DB Kind Tables Mismatch summary counts ...'
GO
--TOWS:DB_KindTablesMismatchSummaryCounts
--WSORDER:1
--WSCOLCOMMENT:NRTABLES:"Nr of tables ( total ) "
--WSCOLCOMMENT:NR_CMN_TNAMES:"Nr of common tables names(!)"
--WSCOLCOMMENT:NR_CMN_TNAMES_WITH_SIG_DIFF_COLL:"Nr of common tables names(!) with a significant diff of collation"
--WSCOLCOMMENT:NR_CMN_TNAMES_WITH_ANY_DIFF_COLL:"Nr of common tables names(!) with a significant diff of collation"
 SELECT
  T1.DB_KIND_NAME
  ,TMAXMIN.MIN_NRTABLES
  ,TMAXMIN.MAX_NRTABLES
  ,NRTABLES
  ,NR_COLS
  ,NR_COLS_DIFF_CI_CS
  ,NR_COLS_DIFF_ANY
  ,NR_CMN_TNAMES
  ,NR_CMN_TNAMES_WITH_SIG_DIFF_COLL
  ,NR_CMN_TNAMES_WITH_ANY_DIFF_COLL
--  ,NR_TNAMES_TABLES_WITH_DIFF_COLLATION
  ,SPURIOUS_TABLES
  ,TABLES_WITH_SPURIOUS_COLUMNS
  ,SPURIOUS_COLUMNS
  ,TABLES_WITH_MORE_THAN_ONE_COLLATION_IN_TABLE
  ,TABLES_WITH_MORE_THAN_ONE_CICS_IN_TABLE

  FROM
  (SELECT DB_KIND_NAME, COUNT(*) NRTABLES FROM [dbo].[VW_DB_TABLE_COLLATION] GROUP BY DB_KIND_NAME) T1
  LEFT OUTER JOIN
	[dbo].[VW_DB_KIND_COLLATION] TMAXMIN
  ON T1.DB_KIND_NAME = TMAXMIN.DB_KIND_NAME

  LEFT OUTER JOIN
-- nr tnames
(SELECT DB_KIND_NAME, COUNT(*) NR_CMN_TNAMES FROM (
SELECT T1.*
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME  FROM [dbo].[VW_DB_TABLE_COLLATION]
   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
   ) T1
  ) T2
   GROUP BY DB_KIND_NAME) NR_CMN_TNAMES
 ON T1.DB_KIND_NAME = NR_CMN_TNAMES.DB_KIND_NAME
  LEFT OUTER JOIN
-- significant deviations
(SELECT DB_KIND_NAME, COUNT(*) NR_CMN_TNAMES_WITH_SIG_DIFF_COLL FROM (
SELECT T1.*,
  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
                       ORDER BY CCOL_Lat_CS, CCOL_CI ) RN
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, (CCOL_Lat_CI + CCOL_SQL_CI) CCOL_CI  FROM [dbo].[VW_DB_TABLE_COLLATION]
   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
   ) T1
  ) T2 WHERE T2.RN = 2   GROUP BY DB_KIND_NAME) NR_CMN_TNAMES_WITH_SIG_DIFF_COLL

    ON T1.DB_KIND_NAME = NR_CMN_TNAMES_WITH_SIG_DIFF_COLL.DB_KIND_NAME
  LEFT OUTER JOIN

  (SELECT DB_KIND_NAME, COUNT(*) NR_CMN_TNAMES_WITH_ANY_DIFF_COLL FROM (
	SELECT T1.*,
	  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
						   ORDER BY CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI ) RN
	  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI FROM [dbo].[VW_DB_TABLE_COLLATION]
	   WHERE NRSPURIOUS_COL = 0 AND SPURIOUS = 0
	   ) T1
	  ) T2 WHERE T2.RN = 2
	  GROUP BY DB_KIND_NAME) NR_CMN_TNAMES_WITH_ANY_DIFF_COLL
   ON T1.DB_KIND_NAME = NR_CMN_TNAMES_WITH_ANY_DIFF_COLL.DB_KIND_NAME
  LEFT OUTER JOIN
  (SELECT DB_KIND_NAME, COUNT(*) NR_TNAMES_WITH_ANY_DIFF_COLL FROM ( SELECT T1.*,
  ROW_NUMBER() OVER ( PARTITION BY  DB_KIND_NAME, TNAME
                       ORDER BY CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI ) RN
  FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME,  CCOL_Lat_CS, CCOL_Lat_CI, CCOL_SQL_CI FROM [dbo].[VW_DB_TABLE_COLLATION] ) T1
  ) T2 WHERE T2.RN = 2   GROUP BY DB_KIND_NAME) NR_TNAMES_WITH_ANY_DIFF_COLL
  ON T1.DB_KIND_NAME = NR_TNAMES_WITH_ANY_DIFF_COLL.DB_KIND_NAME
  LEFT OUTER JOIN
  (SELECT DB_KIND_NAME, COUNT(*) SPURIOUS_TABLES FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE SPURIOUS = 1  GROUP BY DB_KIND_NAME) SPURIOUS_TABLES
  ON T1.DB_KIND_NAME = SPURIOUS_TABLES.DB_KIND_NAME
  LEFT OUTER JOIN
  (SELECT DB_KIND_NAME, COUNT(*) TABLES_WITH_SPURIOUS_COLUMNS FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRSPURIOUS_COL > 0  GROUP BY DB_KIND_NAME) TABLES_WITH_SPURIOUS_COLUMNS
   ON T1.DB_KIND_NAME = TABLES_WITH_SPURIOUS_COLUMNS.DB_KIND_NAME
  LEFT OUTER JOIN
  (SELECT DB_KIND_NAME, SUM(NRSPURIOUS_COL) SPURIOUS_COLUMNS FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRSPURIOUS_COL > 0  GROUP BY DB_KIND_NAME) SPURIOUS_COLUMNS
   ON T1.DB_KIND_NAME = SPURIOUS_COLUMNS.DB_KIND_NAME
  LEFT OUTER JOIN
  (SELECT DB_KIND_NAME, COUNT(*) TABLES_WITH_MORE_THAN_ONE_COLLATION_IN_TABLE FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRCCOL > 1   GROUP BY DB_KIND_NAME) TABLES_WITH_MORE_THAN_ONE_COLLATION_IN_TABLE
   ON T1.DB_KIND_NAME = TABLES_WITH_MORE_THAN_ONE_COLLATION_IN_TABLE.DB_KIND_NAME
  LEFT OUTER JOIN
  (SELECT DB_KIND_NAME, COUNT(*) TABLES_WITH_MORE_THAN_ONE_CICS_IN_TABLE FROM [dbo].[VW_DB_TABLE_COLLATION] WHERE NRCCOLCICS > 1   GROUP BY DB_KIND_NAME) TABLES_WITH_MORE_THAN_ONE_CICS_IN_TABLE
   ON T1.DB_KIND_NAME = TABLES_WITH_MORE_THAN_ONE_CICS_IN_TABLE.DB_KIND_NAME
  LEFT OUTER JOIN [dbo].[VW_DB_KIND_COLL_DIF_COL_COUNT]   COLCNT
   ON T1.DB_KIND_NAME = COLCNT.DB_KIND_NAME

  ORDER BY DB_KIND_NAME
GO



-- SELECT DB_NAME, TNAME, NRCCOLCICS, CCOL_Lat_CI, CCOL_Lat_CS, CCOL_SQL_CI FROM [dbo].[DB_TABLES]  WHERE TNAME = 'ADHOC_ORG_EXTRACT_CONFIG'
-- SELECT DB_NAME, TNAME, CNAME, CCOL FROM [dbo].[DB_TBL_COL]  WHERE TNAME = 'ADHOC_ORG_EXTRACT_CONFIG' AND DB_NAME = 'HrmlPC2Prod'

--SELECT T1.DB_KIND_NAME, DB_NAME, SERVERNAME, DCNAME, TNAME,
--  T1.DBCOL,
-- NRCOLS, NRCCOL, NRCCOLCICS,
-- T1.CCOL_Lat_CS , T1.CCOL_Lat_CI, T1.CCOL_SQL_CI  FROM [dbo].[DB_TABLES]
--GO

--  SELECT * FROM [dbo].[DB_TABLES] WHERE TNAME = 'USER_SESSION'

--   SELECT * FROM [dbo].[TNAME_COUNTS] WHERE TNAME = 'USER_SESSION'
  -- SELECT * FROM [dbo].[DB_KIND_COUNTS] WHERE TNAME = 'USER_SESSION'

SELECT 'Spurious Table vs common table count count'
SELECT DB_KIND_NAME, COUNT( DISTINCT TNAME ) NR_DISTINCT_TABLES
  FROM [dbo].[SPURIOUS_TABLES]
  GROUP BY DB_KIND_NAME
  ORDER BY DB_KIND_NAME
GO

-- ORG_HANA_DRILLTHROUGH_COLUMN
-- ORG_HANA_OLAP_OBJECT_IDENTIFIER

SELECT 'Spurious DB Tables (?) with first DC ... '
--TOWS:DB_Potential_SpuriousTables
SELECT T1.DB_KIND_NAME,
       T1.TNAME,
       ACT_CNT.NRDBS  ACT_CNT,
	   EXP_CNT.CNT_DBS_OF_KIND EXP_CNT,
	   FIRST_DB.DB_NAME FIRST_DB_NAME,
	   FIRST_DB.DCNAME FIRST_DC_NAME,
	   FIRST_DB.SERVERNAME SERVERNAME
 FROM [dbo].[SPURIOUS_TABLES] T1
 LEFT OUTER JOIN
   [dbo].[DB_KIND_COUNTS] EXP_CNT
 ON EXP_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
   LEFT OUTER JOIN [dbo].[TNAME_COUNTS] ACT_CNT
 ON ACT_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
	AND ACT_CNT.TNAME = T1.TNAME
-- pull in the FIRST SERVERNAME
 left join (
   select * from (
        select *, row_number() over (
            partition by DB_KIND_NAME, TNAME
            order by DCDBSRV desc
        ) as row_num
        from [dbo].[DB_TABLES]
    ) as ordered_TBL
    where ordered_TBL.row_num = 1
	) FIRST_DB
  ON FIRST_DB.DB_KIND_NAME = T1.DB_KIND_NAME
     AND FIRST_DB.TNAME = T1.TNAME
GO

SELECT 'DB Tables missing in some DCs (?) incomplete ... '
--TOWS:DB_PotentialMissingTables
SELECT * FROM (
SELECT T1.DB_KIND_NAME,
       T1.TNAME,
       ACT_CNT.NRDBS  ACT_CNT,
	   EXP_CNT.CNT_DBS_OF_KIND EXP_CNT,
	   FIRST_DB.DB_NAME FIRST_DB_NAME,
	   FIRST_DB.DCNAME FIRST_DC_NAME,
	   FIRST_DB.SERVERNAME SERVERNAME
 FROM [dbo].[SPURIOUS_TABLES] T1
 LEFT OUTER JOIN
   [dbo].[DB_KIND_COUNTS] EXP_CNT
 ON EXP_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
   LEFT OUTER JOIN [dbo].[TNAME_COUNTS] ACT_CNT
 ON ACT_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
	AND ACT_CNT.TNAME = T1.TNAME
-- pull in the FIRST SERVERNAME
 left join (
   select * from (
        select *, row_number() over (
            partition by DB_KIND_NAME, TNAME
            order by DCDBSRV desc
        ) as row_num
        from [dbo].[DB_TABLES]
    ) as ordered_TBL
    where ordered_TBL.row_num = 1
	) FIRST_DB
  ON FIRST_DB.DB_KIND_NAME = T1.DB_KIND_NAME
     AND FIRST_DB.TNAME = T1.TNAME ) TX
 WHERE ( EXP_CNT - ACT_CNT ) <2 AND EXP_CNT > 4 AND  FIRST_DB_NAME <> 'WST_17Nov'

GO
--- Spurious columns in COMMON TABLES



-- same procedure as above.

-- for every [tkind,tname,cname] compute number of COL KIND COUNTS
DROP TABLE IF EXISTS [dbo].[CNAME_COUNTS];
GO
SELECT *
   INTO [dbo].[CNAME_COUNTS]
   FROM (
SELECT DB_KIND_NAME, DB_KIND, TNAME, CNAME, COUNT( DISTINCT DCDBSRV ) NRDBS
   FROM [dbo].[COMMON_TBL_COL]
   GROUP BY DB_KIND_NAME, DB_KIND, TNAME, CNAME
   ) T1
GO
-- we can use the Simple DB_KIND_NAME count here as we are dealing with common tables!
-- these exist in all

-- columns which are not in all dbs ->
DROP TABLE IF EXISTS [dbo].[SPURIOUS_COLUMNS];
GO

SELECT T1.DB_KIND_NAME, TNAME , CNAME
  INTO [dbo].[SPURIOUS_COLUMNS]
  FROM [dbo].[CNAME_COUNTS] T1
  INNER JOIN [dbo].[DB_KIND_COUNTS] T2
  ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
  AND T1.NRDBS != T2.CNT_DBS_OF_KIND
GO
-- columns which are in all dbs ->
DROP TABLE IF EXISTS [dbo].[COMMON_COLUMNS];
GO

SELECT T1.DB_KIND_NAME, TNAME , CNAME
  INTO [dbo].[COMMON_COLUMNS]
  FROM [dbo].[CNAME_COUNTS] T1
  INNER JOIN [dbo].[DB_KIND_COUNTS] T2
  ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
  AND T1.NRDBS = T2.CNT_DBS_OF_KIND
GO


SELECT 'Columns which may be spurios DB Columns (?) ... (or are missing, see below) '
SELECT T1.DB_KIND_NAME,
       T1.TNAME,
	   T1.CNAME,
       ACT_CNT.NRDBS  ACT_CNT,
	   EXP_CNT.CNT_DBS_OF_KIND EXP_CNT,
	   FIRST_TBL.DB_NAME FIRST_PRESENT_DB_NAME,
	   FIRST_TBL.DCNAME FIRST_PRESENT_DC_NAME,
	   FIRST_TBL.SERVERNAME FIRST_PRESENT_SERVERNAME
 FROM [dbo].[SPURIOUS_COLUMNS] T1
 LEFT OUTER JOIN
   [dbo].[DB_KIND_COUNTS] EXP_CNT
 ON EXP_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
   LEFT OUTER JOIN [dbo].[CNAME_COUNTS] ACT_CNT
 ON ACT_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
    AND ACT_CNT.CNAME = T1.CNAME
	AND ACT_CNT.TNAME = T1.TNAME
-- pull in the FIRST SERVERNAME where it is present
 left join (
   select * from (
        select *, row_number() over (
            partition by DB_KIND_NAME, TNAME, CNAME
            order by DCDBSRV desc
        ) as row_num
        from [dbo].[COMMON_TBL_COL]
    ) as ordered_TBL
    where ordered_TBL.row_num = 1
	) FIRST_TBL
  ON FIRST_TBL.DB_KIND_NAME = T1.DB_KIND_NAME
     AND FIRST_TBL.TNAME = T1.TNAME
	 AND FIRST_TBL.CNAME = T1.CNAME
	 	 ORDER BY DB_KIND_NAME, TNAME, CNAME , FIRST_DB_NAME

SELECT 'Colums which are missing (?) '
SELECT T1.DB_KIND_NAME, T1.TNAME, SC.CNAME ,
			ACT_CNT.NRDBS  ACT_CNT,
			EXP_CNT.CNT_DBS_OF_KIND EXP_CNT,
		   T1.SERVERNAME, T1.DCNAME , T1.DB_NAME
			-- ,TPRESENT.CNAME
		FROM
		[dbo].[SPURIOUS_COLUMNS]  SC
		INNER JOIN
		(
			SELECT T1X.DCDBSRV,T1X.TNAME, DB_NAME, SERVERNAME, DCNAME, DB_KIND_NAME FROM
			(SELECT DISTINCT DCDBSRV,TNAME, DB_NAME, SERVERNAME, DCNAME, DB_KIND_NAME FROM [dbo].[COMMON_TBL_COL]
			) T1X
		) T1
	ON T1.TNAME = SC.TNAME
	LEFT OUTER JOIN
	  [dbo].[COMMON_TBL_COL] TPRESENT
	  ON TPRESENT.CNAME = SC.CNAME
	  AND TPRESENT.TNAME = T1.TNAME
      AND TPRESENT.DCDBSRV = T1.DCDBSRV
 LEFT OUTER JOIN
   [dbo].[DB_KIND_COUNTS] EXP_CNT
 ON EXP_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
   LEFT OUTER JOIN [dbo].[CNAME_COUNTS] ACT_CNT
 ON ACT_CNT.DB_KIND_NAME = T1.DB_KIND_NAME
    AND ACT_CNT.CNAME = SC.CNAME
	AND ACT_CNT.TNAME = T1.TNAME
WHERE TPRESENT.CNAME IS NULL
ORDER BY T1.DB_KIND_NAME, T1.TNAME, SC.CNAME, T1.DCNAME, T1.SERVERNAME, T1.DB_NAME


-- ==========================================================
-- Different column collations in "Common columns"

SELECT 'Nr of columns with a significant Collation Difference ( CI vs CS ) in common tables'
SELECT COUNT(*) FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOLCICS < T2.CCOLCICS
   ) T1
) T0


SELECT 'Nr of common table columns with Collation Differences'

SELECT (
SELECT COUNT(*) FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOLCICS < T2.CCOLCICS
   ) T1
) T0  ) DIFF_CI_CS
,
( SELECT COUNT(*)
 FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOL < T2.CCOL
   ) T1
) T0 ) DIFF_ANY ,
( SELECT COUNT(*) FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME, CNAME  FROM [dbo].[COMMON_TBL_COL] ) T01 ) NR_COMMON_COLS


SELECT 'NR of Collation differences in Common Tables'
 ---
 --- TOWS:DB_KIND_CMN_TBL_COL_COLL_DIFF_CNT
SELECT
  TC.DB_KIND_NAME, COALESCE(DIFF_CI_CS,0) DIFF_CI_CS, COALESCE(DIFF_ANY,0) DIFF_ANY, NR_COLS
FROM
( SELECT DB_KIND_NAME, COUNT(*) NR_COLS FROM ( SELECT DISTINCT DB_KIND_NAME, TNAME, CNAME  FROM [dbo].[COMMON_TBL_COL] ) T01
GROUP BY T01.DB_KIND_NAME
) TC
LEFT OUTER JOIN
( SELECT DB_KIND_NAME, COUNT(*) DIFF_CI_CS
   FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOLCICS < T2.CCOLCICS
   ) T1
) T0
GROUP BY T0.DB_KIND_NAME
 ) TA
ON TC.DB_KIND_NAME = TA.DB_KIND_NAME
LEFT OUTER JOIN
( SELECT DB_KIND_NAME, COUNT(*)	DIFF_ANY
 FROM
(
SELECT DISTINCT * FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOL < T2.CCOL
   ) T1
) T0
GROUP BY T0.DB_KIND_NAME ) TB
ON TC.DB_KIND_NAME = TB.DB_KIND_NAME
ORDER BY DB_KIND_NAME

GO

DROP VIEW IF EXISTS [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_SIG_DIFF];
GO
CREATE VIEW [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_SIG_DIFF] AS (
SELECT
	DB_KIND_NAME, TNAME, CNAME,
	( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX
	    WHERE TUX.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX.TNAME = TU.TNAME
		AND TUX.CNAME = TU.CNAME
	    ) NRDBS
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX
	    WHERE TUX.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX.TNAME = TU.TNAME
		AND TUX.CNAME = TU.CNAME
		AND TUX.CCOL = 'Latin1_General_CS_AS'
	    ) CCOL_Lat_CS
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX1
	    WHERE TUX1.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX1.TNAME = TU.TNAME
		AND TUX1.CNAME = TU.CNAME
		AND TUX1.CCOL = 'Latin1_General_CI_AS'
	    ) CCOL_Lat_CI
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX2
	    WHERE TUX2.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX2.TNAME = TU.TNAME
		AND TUX2.CNAME = TU.CNAME
		AND TUX2.CCOL = 'SQL_Latin1_General_CP1_CI_AS'
	    ) CCOL_SQL_CI
	FROM

( SELECT DISTINCT DB_KIND_NAME, TNAME, CNAME FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME, T1.CCOLCICS, T2.CCOLCICS T2CO FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOLCICS < T2.CCOLCICS
   ) T1
) TU
)
GO

SELECT 'Serious Column Collation differences (CI vs CS) '
--TOWS:DB_KIND_SERIOUS_COLL_DIFF
--WSCOMMENT:"Serious Column Collation differences ( CI vs CS )"
--WSFIX:1,3
--WSCOLCOMMENT:NRDBS:"Nr of DBS with this column"
--WSCOLCOMMENT:CCOL_Lat_CS:"Nr of Columns with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:CCOL_Lat_CI:"Nr of Columns with Latin1_General_CI_AS collation"
--WSCOLCOMMENT:CCOL_SQL_CI:"Nr of Columsn with SQL_Latin1_General_CP1_CI_AS collation"
SELECT * FROM [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_SIG_DIFF] ORDER BY DB_KIND_NAME, TNAME, CNAME
GO

-- all collation differences
DROP VIEW IF EXISTS [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_ANY_DIFF];
GO
CREATE VIEW [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_ANY_DIFF] AS (
SELECT
	DB_KIND_NAME, TNAME, CNAME,
	( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX
	    WHERE TUX.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX.TNAME = TU.TNAME
		AND TUX.CNAME = TU.CNAME
	    ) NRDBS
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX
	    WHERE TUX.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX.TNAME = TU.TNAME
		AND TUX.CNAME = TU.CNAME
		AND TUX.CCOL = 'Latin1_General_CS_AS'
	    ) CCOL_Lat_CS
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX1
	    WHERE TUX1.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX1.TNAME = TU.TNAME
		AND TUX1.CNAME = TU.CNAME
		AND TUX1.CCOL = 'Latin1_General_CI_AS'
	    ) CCOL_Lat_CI
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX2
	    WHERE TUX2.DB_KIND_NAME = TU.DB_KIND_NAME
		AND TUX2.TNAME = TU.TNAME
		AND TUX2.CNAME = TU.CNAME
		AND TUX2.CCOL = 'SQL_Latin1_General_CP1_CI_AS'
	    ) CCOL_SQL_CI
	FROM

( SELECT DISTINCT DB_KIND_NAME, TNAME, CNAME FROM (
SELECT T1.DB_KIND_NAME, T1.TNAME, T1.CNAME, T1.CCOLCICS, T2.CCOLCICS T2CO FROM
   [dbo].[COMMON_TBL_COL] T1
   INNER JOIN
   [dbo].[COMMON_TBL_COL] T2
   ON
   T1.DB_KIND = T2.DB_KIND
   AND T1.TNAME = T2.TNAME
   AND T1.CNAME = T2.CNAME
   WHERE T1.CCOL < T2.CCOL -- any difference
   ) T1
) TU
)
GO
SELECT * FROM [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_ANY_DIFF] WHERE TNAME = 'ODS_QUERY'
GO

-- we do not want to list all columns here, we only list
-- a) spurious columns,

SELECT DISTINCT CCOL FROM [dbo].[COMMON_TBL_COL] WHERE DB_KIND_NAME = 'Hrml' and TNAME = 'CRON_JOB' and CNAME = 'JOB_NAME'


SELECT DISTINCT CCOL, COUNT(*) FROM [dbo].[COMMON_TBL_COL] WHERE DB_KIND_NAME = 'Hrml' and TNAME = 'CRON_JOB' and CNAME = 'JOB_NAME'

-- DB Collations
DROP VIEW IF EXISTS [dbo].[VW_COL_COLLATIONS];

GO

CREATE VIEW [dbo].[VW_COL_COLLATIONS] AS SELECT DCNAME, DB_NAME, SERVERNAME, DB_KIND,
DB_KIND_NAME, TNAME, CNAME, CCOL, CCOLCICS, COUNT( DISTINCT TNAME) NRTABLES, COUNT( DISTINCT (TNAME + CNAME) ) NRCOLS,
  COUNT ( DISTINCT CCOL )     NRCCOL,
  COUNT ( DISTINCT CCOLCICS ) NRCCOLCICS
FROM [dbo].[DB_TBL_COL]
WHERE DB_KIND > 0
GROUP BY DCNAME, DB_NAME, SERVERNAME, DB_KIND, DB_KIND_NAME, DBCOL, DBCOLCICS;
GO



SELECT 'Same Columns with different collations ...'

SELECT  T1.DB_KIND_NAME, T1.CCOLCICS, T1.DBCOL, TCNT.CNT NRSAMECOLDBS, T1.DB_NAME, T1.DCNAME
FROM
 (	SELECT DISTINCT DB_KIND_NAME, DBCOLCICS, DBCOL, DB_NAME, DCNAME
	FROM [dbo].VW_DB_COLLATIONS
	WHERE DB_KIND_NAME IN ( SELECT DB_KIND_NAME FROM [dbo].[VW_DB_COLS_DIFFERING] )
	)  T1
LEFT OUTER JOIN
 (
   SELECT DB_KIND_NAME, COUNT( * ) CNT , DBCOL FROM
		(	SELECT DISTINCT DB_KIND_NAME, DBCOLCICS, DBCOL, DB_NAME, DCNAME
			FROM [dbo].VW_DB_COLLATIONS
			WHERE DB_KIND_NAME IN ( SELECT DB_KIND_NAME FROM [dbo].[VW_DB_COLS_DIFFERING] ) ) T00
	GROUP BY DB_KIND_NAME, DBCOL
  ) TCNT
ON T1.DB_KIND_NAME = TCNT.DB_KIND_NAME
AND T1.DBCOL = TCNT.DBCOL
ORDER BY DB_KIND_NAME, DBCOLCICS, DBCOL, DCNAME, DB_NAME


GO

-- DUMP ALL COLS --

-- We only use these tables :
-- common tables +
-- ORG_HANA_DRILLTHROUGH_COLUMN
-- ORG_HANA_OLAP_OBJECT_IDENTIFIER

DROP VIEW IF EXISTS [dbo].[VW DB_COMMON_TNAME_CNAME_COLL]
GO
CREATE VIEW [dbo].[VW DB_COMMON_TNAME_CNAME_COLL]  AS
SELECT T1.DB_KIND_NAME, DB_NAME, SERVERNAME ,DCNAME, DBCOL,  T1.TNAME, T1.CNAME,  T1.CCOL , T1.CID
  ,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX
	    WHERE TUX.DB_KIND_NAME = T1.DB_KIND_NAME
		AND TUX.TNAME = T1.TNAME
		AND TUX.CNAME = T1.CNAME
	    ) NRDBS
  , (CASE WHEN SIGDIFF.CNAME IS NOT NULL THEN 1 ELSE 0 END) SIGDIFF
  , (CASE WHEN ANYDIFF.CNAME IS NOT NULL THEN 1 ELSE 0 END) ANYDIFF
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX
	    WHERE TUX.DB_KIND_NAME = T1.DB_KIND_NAME
		AND TUX.TNAME = T1.TNAME
		AND TUX.CNAME = T1.CNAME
		AND TUX.CCOL = 'Latin1_General_CS_AS'
	    ) CCOL_Lat_CS
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX1
	    WHERE TUX1.DB_KIND_NAME = T1.DB_KIND_NAME
		AND TUX1.TNAME = T1.TNAME
		AND TUX1.CNAME = T1.CNAME
		AND TUX1.CCOL = 'Latin1_General_CI_AS'
	    ) CCOL_Lat_CI
	,( SELECT COUNT(*) CNT_TOTAL FROM [dbo].[COMMON_TBL_COL] TUX2
	    WHERE TUX2.DB_KIND_NAME = T1.DB_KIND_NAME
		AND TUX2.TNAME = T1.TNAME
		AND TUX2.CNAME = T1.CNAME
		AND TUX2.CCOL = 'SQL_Latin1_General_CP1_CI_AS'
	    ) CCOL_SQL_CI
FROM [dbo].[DB_TBL_COL] T1
LEFT OUTER JOIN [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_ANY_DIFF] T2
ON T1.DB_KIND_NAME = T2.DB_KIND_NAME
	 AND T1.TNAME = T2.TNAME
	 AND T1.CNAME = T2.CNAME
LEFT OUTER JOIN [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_ANY_DIFF]  ANYDIFF
ON T1.DB_KIND_NAME = ANYDIFF.DB_KIND_NAME
	AND T1.TNAME = ANYDIFF.TNAME
	AND T1.CNAME = ANYDIFF.CNAME
LEFT OUTER JOIN  [dbo].[VW_DB_KIND_TNAME_CNAME_COLL_SIG_DIFF] SIGDIFF
ON T1.DB_KIND_NAME = SIGDIFF.DB_KIND_NAME
	AND T1.TNAME = SIGDIFF.TNAME
	AND T1.CNAME = SIGDIFF.CNAME
WHERE
 ( T1.TNAME IN ( SELECT DISTINCT TNAME FROM [dbo].[COMMON_TABLES] )
  OR T1.TNAME IN ( 'ORG_HANA_DRILLTHROUGH_COLUMN', 'ORG_HANA_OLAP_OBJECT_IDENTIFIER')
 )
GO

SELECT 'Column collations per DC for common tables'
--TOWS:DB_COL_Collations_Common
--WSFIX:1,7
--WSCOLCOMMENT:DBCOL:"Database Collation"
--WSCOLCOMMENT:SPURIOUS:"DB may be spurious( is not in all DBs of Kind), Filter = 1"
--WSCOLCOMMENT:DB_Lat_CS:"Nr of DBs with Latin1_General_CS_AS collation"
--WSCOLCOMMENT:NRDBS:"Nr of DBS with this column (only if diff)"
--WSCOLCOMMENT:SIGDIFF:"Significant Difference ( CI-CS ) between columns in DBs (Filter = 1)"
--WSCOLCOMMENT:ANYDIFF:"Any Collation Difference between columns in DBs (Filter = 1)"
--WSCOLCOMMENT:CCOL_Lat_CS:"Nr of Columns with Latin1_General_CS_AS collation (only if diff)"
--WSCOLCOMMENT:CCOL_Lat_CI:"Nr of Columns with Latin1_General_CI_AS collation (only if diff)"
--WSCOLCOMMENT:CCOL_SQL_CI:"Nr of Columsn with SQL_Latin1_General_CP1_CI_AS collation"
SELECT * FROM  [dbo].[VW DB_COMMON_TNAME_CNAME_COLL]
  ORDER BY TNAME, CNAME, CCOL , DCNAME, DB_NAME
GO


-- ================================
-- These are leftover tables ... with a different schema
SELECT 'Remove all tables name SITE_CONFIG with column SITE_ID  (Corpses in Hrml dbs)'
SELECT DISTINCT WSNAME, DB_NAME, DB_KIND, TNAME, CNAME, SERVERNAME
  FROM [dbo].[DB_TBL_COL_COLLATION]
  WHERE TNAME = 'SITE_CONFIG' AND CNAME = 'SITE_ID'


-- =  'TENANT_PREFERRED_TIMEZONE'
